# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/work/AnaCarvalho-Portfolio/AnaCarvalho-Portfolio

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/work/AnaCarvalho-Portfolio/AnaCarvalho-Portfolio/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/AnaCarvalho-Portfolio/AnaCarvalho-Portfolio/build/CMakeFiles /home/runner/work/AnaCarvalho-Portfolio/AnaCarvalho-Portfolio/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/AnaCarvalho-Portfolio/AnaCarvalho-Portfolio/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/runner/work/AnaCarvalho-Portfolio/AnaCarvalho-Portfolio/build/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Minigin

# Build rule for target.
Minigin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Minigin
.PHONY : Minigin

# fast build rule for target.
Minigin/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/build
.PHONY : Minigin/fast

#=============================================================================
# Target rules for targets named Portfolio_web

# Build rule for target.
Portfolio_web: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Portfolio_web
.PHONY : Portfolio_web

# fast build rule for target.
Portfolio_web/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Portfolio_web.dir/build.make CMakeFiles/Portfolio_web.dir/build
.PHONY : Portfolio_web/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named glm

# Build rule for target.
glm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glm
.PHONY : glm

# fast build rule for target.
glm/fast:
	$(MAKE) $(MAKESILENT) -f _deps/glm-build/glm/CMakeFiles/glm.dir/build.make _deps/glm-build/glm/CMakeFiles/glm.dir/build
.PHONY : glm/fast

#=============================================================================
# Target rules for targets named SDL3-static

# Build rule for target.
SDL3-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL3-static
.PHONY : SDL3-static

# fast build rule for target.
SDL3-static/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl3-build/CMakeFiles/SDL3-static.dir/build.make _deps/sdl3-build/CMakeFiles/SDL3-static.dir/build
.PHONY : SDL3-static/fast

#=============================================================================
# Target rules for targets named SDL3_test

# Build rule for target.
SDL3_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL3_test
.PHONY : SDL3_test

# fast build rule for target.
SDL3_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl3-build/CMakeFiles/SDL3_test.dir/build.make _deps/sdl3-build/CMakeFiles/SDL3_test.dir/build
.PHONY : SDL3_test/fast

#=============================================================================
# Target rules for targets named SDL_uclibc

# Build rule for target.
SDL_uclibc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL_uclibc
.PHONY : SDL_uclibc

# fast build rule for target.
SDL_uclibc/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl3-build/CMakeFiles/SDL_uclibc.dir/build.make _deps/sdl3-build/CMakeFiles/SDL_uclibc.dir/build
.PHONY : SDL_uclibc/fast

#=============================================================================
# Target rules for targets named SDL3_ttf-static

# Build rule for target.
SDL3_ttf-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL3_ttf-static
.PHONY : SDL3_ttf-static

# fast build rule for target.
SDL3_ttf-static/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl3_ttf-build/CMakeFiles/SDL3_ttf-static.dir/build.make _deps/sdl3_ttf-build/CMakeFiles/SDL3_ttf-static.dir/build
.PHONY : SDL3_ttf-static/fast

Minigin/FPSComponent.o: Minigin/FPSComponent.cpp.o
.PHONY : Minigin/FPSComponent.o

# target to build an object file
Minigin/FPSComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/FPSComponent.cpp.o
.PHONY : Minigin/FPSComponent.cpp.o

Minigin/FPSComponent.i: Minigin/FPSComponent.cpp.i
.PHONY : Minigin/FPSComponent.i

# target to preprocess a source file
Minigin/FPSComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/FPSComponent.cpp.i
.PHONY : Minigin/FPSComponent.cpp.i

Minigin/FPSComponent.s: Minigin/FPSComponent.cpp.s
.PHONY : Minigin/FPSComponent.s

# target to generate assembly for a file
Minigin/FPSComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/FPSComponent.cpp.s
.PHONY : Minigin/FPSComponent.cpp.s

Minigin/Font.o: Minigin/Font.cpp.o
.PHONY : Minigin/Font.o

# target to build an object file
Minigin/Font.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/Font.cpp.o
.PHONY : Minigin/Font.cpp.o

Minigin/Font.i: Minigin/Font.cpp.i
.PHONY : Minigin/Font.i

# target to preprocess a source file
Minigin/Font.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/Font.cpp.i
.PHONY : Minigin/Font.cpp.i

Minigin/Font.s: Minigin/Font.cpp.s
.PHONY : Minigin/Font.s

# target to generate assembly for a file
Minigin/Font.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/Font.cpp.s
.PHONY : Minigin/Font.cpp.s

Minigin/GameObject.o: Minigin/GameObject.cpp.o
.PHONY : Minigin/GameObject.o

# target to build an object file
Minigin/GameObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/GameObject.cpp.o
.PHONY : Minigin/GameObject.cpp.o

Minigin/GameObject.i: Minigin/GameObject.cpp.i
.PHONY : Minigin/GameObject.i

# target to preprocess a source file
Minigin/GameObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/GameObject.cpp.i
.PHONY : Minigin/GameObject.cpp.i

Minigin/GameObject.s: Minigin/GameObject.cpp.s
.PHONY : Minigin/GameObject.s

# target to generate assembly for a file
Minigin/GameObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/GameObject.cpp.s
.PHONY : Minigin/GameObject.cpp.s

Minigin/Gamepad.o: Minigin/Gamepad.cpp.o
.PHONY : Minigin/Gamepad.o

# target to build an object file
Minigin/Gamepad.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/Gamepad.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/Minigin/Gamepad.cpp.o
.PHONY : Minigin/Gamepad.cpp.o

Minigin/Gamepad.i: Minigin/Gamepad.cpp.i
.PHONY : Minigin/Gamepad.i

# target to preprocess a source file
Minigin/Gamepad.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/Gamepad.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/Minigin/Gamepad.cpp.i
.PHONY : Minigin/Gamepad.cpp.i

Minigin/Gamepad.s: Minigin/Gamepad.cpp.s
.PHONY : Minigin/Gamepad.s

# target to generate assembly for a file
Minigin/Gamepad.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/Gamepad.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/Minigin/Gamepad.cpp.s
.PHONY : Minigin/Gamepad.cpp.s

Minigin/InputManager.o: Minigin/InputManager.cpp.o
.PHONY : Minigin/InputManager.o

# target to build an object file
Minigin/InputManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/InputManager.cpp.o
.PHONY : Minigin/InputManager.cpp.o

Minigin/InputManager.i: Minigin/InputManager.cpp.i
.PHONY : Minigin/InputManager.i

# target to preprocess a source file
Minigin/InputManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/InputManager.cpp.i
.PHONY : Minigin/InputManager.cpp.i

Minigin/InputManager.s: Minigin/InputManager.cpp.s
.PHONY : Minigin/InputManager.s

# target to generate assembly for a file
Minigin/InputManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/InputManager.cpp.s
.PHONY : Minigin/InputManager.cpp.s

Minigin/MiniaudioSoundSystem.o: Minigin/MiniaudioSoundSystem.cpp.o
.PHONY : Minigin/MiniaudioSoundSystem.o

# target to build an object file
Minigin/MiniaudioSoundSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/MiniaudioSoundSystem.cpp.o
.PHONY : Minigin/MiniaudioSoundSystem.cpp.o

Minigin/MiniaudioSoundSystem.i: Minigin/MiniaudioSoundSystem.cpp.i
.PHONY : Minigin/MiniaudioSoundSystem.i

# target to preprocess a source file
Minigin/MiniaudioSoundSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/MiniaudioSoundSystem.cpp.i
.PHONY : Minigin/MiniaudioSoundSystem.cpp.i

Minigin/MiniaudioSoundSystem.s: Minigin/MiniaudioSoundSystem.cpp.s
.PHONY : Minigin/MiniaudioSoundSystem.s

# target to generate assembly for a file
Minigin/MiniaudioSoundSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/MiniaudioSoundSystem.cpp.s
.PHONY : Minigin/MiniaudioSoundSystem.cpp.s

Minigin/Minigin.o: Minigin/Minigin.cpp.o
.PHONY : Minigin/Minigin.o

# target to build an object file
Minigin/Minigin.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/Minigin.cpp.o
.PHONY : Minigin/Minigin.cpp.o

Minigin/Minigin.i: Minigin/Minigin.cpp.i
.PHONY : Minigin/Minigin.i

# target to preprocess a source file
Minigin/Minigin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/Minigin.cpp.i
.PHONY : Minigin/Minigin.cpp.i

Minigin/Minigin.s: Minigin/Minigin.cpp.s
.PHONY : Minigin/Minigin.s

# target to generate assembly for a file
Minigin/Minigin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/Minigin.cpp.s
.PHONY : Minigin/Minigin.cpp.s

Minigin/RenderComponent.o: Minigin/RenderComponent.cpp.o
.PHONY : Minigin/RenderComponent.o

# target to build an object file
Minigin/RenderComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/RenderComponent.cpp.o
.PHONY : Minigin/RenderComponent.cpp.o

Minigin/RenderComponent.i: Minigin/RenderComponent.cpp.i
.PHONY : Minigin/RenderComponent.i

# target to preprocess a source file
Minigin/RenderComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/RenderComponent.cpp.i
.PHONY : Minigin/RenderComponent.cpp.i

Minigin/RenderComponent.s: Minigin/RenderComponent.cpp.s
.PHONY : Minigin/RenderComponent.s

# target to generate assembly for a file
Minigin/RenderComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/RenderComponent.cpp.s
.PHONY : Minigin/RenderComponent.cpp.s

Minigin/Renderer.o: Minigin/Renderer.cpp.o
.PHONY : Minigin/Renderer.o

# target to build an object file
Minigin/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/Renderer.cpp.o
.PHONY : Minigin/Renderer.cpp.o

Minigin/Renderer.i: Minigin/Renderer.cpp.i
.PHONY : Minigin/Renderer.i

# target to preprocess a source file
Minigin/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/Renderer.cpp.i
.PHONY : Minigin/Renderer.cpp.i

Minigin/Renderer.s: Minigin/Renderer.cpp.s
.PHONY : Minigin/Renderer.s

# target to generate assembly for a file
Minigin/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/Renderer.cpp.s
.PHONY : Minigin/Renderer.cpp.s

Minigin/ResourceManager.o: Minigin/ResourceManager.cpp.o
.PHONY : Minigin/ResourceManager.o

# target to build an object file
Minigin/ResourceManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/ResourceManager.cpp.o
.PHONY : Minigin/ResourceManager.cpp.o

Minigin/ResourceManager.i: Minigin/ResourceManager.cpp.i
.PHONY : Minigin/ResourceManager.i

# target to preprocess a source file
Minigin/ResourceManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/ResourceManager.cpp.i
.PHONY : Minigin/ResourceManager.cpp.i

Minigin/ResourceManager.s: Minigin/ResourceManager.cpp.s
.PHONY : Minigin/ResourceManager.s

# target to generate assembly for a file
Minigin/ResourceManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/ResourceManager.cpp.s
.PHONY : Minigin/ResourceManager.cpp.s

Minigin/RotatorComponent.o: Minigin/RotatorComponent.cpp.o
.PHONY : Minigin/RotatorComponent.o

# target to build an object file
Minigin/RotatorComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/RotatorComponent.cpp.o
.PHONY : Minigin/RotatorComponent.cpp.o

Minigin/RotatorComponent.i: Minigin/RotatorComponent.cpp.i
.PHONY : Minigin/RotatorComponent.i

# target to preprocess a source file
Minigin/RotatorComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/RotatorComponent.cpp.i
.PHONY : Minigin/RotatorComponent.cpp.i

Minigin/RotatorComponent.s: Minigin/RotatorComponent.cpp.s
.PHONY : Minigin/RotatorComponent.s

# target to generate assembly for a file
Minigin/RotatorComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/RotatorComponent.cpp.s
.PHONY : Minigin/RotatorComponent.cpp.s

Minigin/Scene.o: Minigin/Scene.cpp.o
.PHONY : Minigin/Scene.o

# target to build an object file
Minigin/Scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/Scene.cpp.o
.PHONY : Minigin/Scene.cpp.o

Minigin/Scene.i: Minigin/Scene.cpp.i
.PHONY : Minigin/Scene.i

# target to preprocess a source file
Minigin/Scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/Scene.cpp.i
.PHONY : Minigin/Scene.cpp.i

Minigin/Scene.s: Minigin/Scene.cpp.s
.PHONY : Minigin/Scene.s

# target to generate assembly for a file
Minigin/Scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/Scene.cpp.s
.PHONY : Minigin/Scene.cpp.s

Minigin/SceneManager.o: Minigin/SceneManager.cpp.o
.PHONY : Minigin/SceneManager.o

# target to build an object file
Minigin/SceneManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/SceneManager.cpp.o
.PHONY : Minigin/SceneManager.cpp.o

Minigin/SceneManager.i: Minigin/SceneManager.cpp.i
.PHONY : Minigin/SceneManager.i

# target to preprocess a source file
Minigin/SceneManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/SceneManager.cpp.i
.PHONY : Minigin/SceneManager.cpp.i

Minigin/SceneManager.s: Minigin/SceneManager.cpp.s
.PHONY : Minigin/SceneManager.s

# target to generate assembly for a file
Minigin/SceneManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/SceneManager.cpp.s
.PHONY : Minigin/SceneManager.cpp.s

Minigin/ServiceLocator.o: Minigin/ServiceLocator.cpp.o
.PHONY : Minigin/ServiceLocator.o

# target to build an object file
Minigin/ServiceLocator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/ServiceLocator.cpp.o
.PHONY : Minigin/ServiceLocator.cpp.o

Minigin/ServiceLocator.i: Minigin/ServiceLocator.cpp.i
.PHONY : Minigin/ServiceLocator.i

# target to preprocess a source file
Minigin/ServiceLocator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/ServiceLocator.cpp.i
.PHONY : Minigin/ServiceLocator.cpp.i

Minigin/ServiceLocator.s: Minigin/ServiceLocator.cpp.s
.PHONY : Minigin/ServiceLocator.s

# target to generate assembly for a file
Minigin/ServiceLocator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/ServiceLocator.cpp.s
.PHONY : Minigin/ServiceLocator.cpp.s

Minigin/TextComponent.o: Minigin/TextComponent.cpp.o
.PHONY : Minigin/TextComponent.o

# target to build an object file
Minigin/TextComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/TextComponent.cpp.o
.PHONY : Minigin/TextComponent.cpp.o

Minigin/TextComponent.i: Minigin/TextComponent.cpp.i
.PHONY : Minigin/TextComponent.i

# target to preprocess a source file
Minigin/TextComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/TextComponent.cpp.i
.PHONY : Minigin/TextComponent.cpp.i

Minigin/TextComponent.s: Minigin/TextComponent.cpp.s
.PHONY : Minigin/TextComponent.s

# target to generate assembly for a file
Minigin/TextComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/TextComponent.cpp.s
.PHONY : Minigin/TextComponent.cpp.s

Minigin/Texture2D.o: Minigin/Texture2D.cpp.o
.PHONY : Minigin/Texture2D.o

# target to build an object file
Minigin/Texture2D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/Texture2D.cpp.o
.PHONY : Minigin/Texture2D.cpp.o

Minigin/Texture2D.i: Minigin/Texture2D.cpp.i
.PHONY : Minigin/Texture2D.i

# target to preprocess a source file
Minigin/Texture2D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/Texture2D.cpp.i
.PHONY : Minigin/Texture2D.cpp.i

Minigin/Texture2D.s: Minigin/Texture2D.cpp.s
.PHONY : Minigin/Texture2D.s

# target to generate assembly for a file
Minigin/Texture2D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/Texture2D.cpp.s
.PHONY : Minigin/Texture2D.cpp.s

Minigin/Transform.o: Minigin/Transform.cpp.o
.PHONY : Minigin/Transform.o

# target to build an object file
Minigin/Transform.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/Transform.cpp.o
.PHONY : Minigin/Transform.cpp.o

Minigin/Transform.i: Minigin/Transform.cpp.i
.PHONY : Minigin/Transform.i

# target to preprocess a source file
Minigin/Transform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/Transform.cpp.i
.PHONY : Minigin/Transform.cpp.i

Minigin/Transform.s: Minigin/Transform.cpp.s
.PHONY : Minigin/Transform.s

# target to generate assembly for a file
Minigin/Transform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minigin.dir/build.make CMakeFiles/Minigin.dir/Minigin/Transform.cpp.s
.PHONY : Minigin/Transform.cpp.s

Portfolio/Main.o: Portfolio/Main.cpp.o
.PHONY : Portfolio/Main.o

# target to build an object file
Portfolio/Main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Portfolio_web.dir/build.make CMakeFiles/Portfolio_web.dir/Portfolio/Main.cpp.o
.PHONY : Portfolio/Main.cpp.o

Portfolio/Main.i: Portfolio/Main.cpp.i
.PHONY : Portfolio/Main.i

# target to preprocess a source file
Portfolio/Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Portfolio_web.dir/build.make CMakeFiles/Portfolio_web.dir/Portfolio/Main.cpp.i
.PHONY : Portfolio/Main.cpp.i

Portfolio/Main.s: Portfolio/Main.cpp.s
.PHONY : Portfolio/Main.s

# target to generate assembly for a file
Portfolio/Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Portfolio_web.dir/build.make CMakeFiles/Portfolio_web.dir/Portfolio/Main.cpp.s
.PHONY : Portfolio/Main.cpp.s

_deps/imgui-src/backends/imgui_impl_sdl3.o: _deps/imgui-src/backends/imgui_impl_sdl3.cpp.o
.PHONY : _deps/imgui-src/backends/imgui_impl_sdl3.o

# target to build an object file
_deps/imgui-src/backends/imgui_impl_sdl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/backends/imgui_impl_sdl3.cpp.o
.PHONY : _deps/imgui-src/backends/imgui_impl_sdl3.cpp.o

_deps/imgui-src/backends/imgui_impl_sdl3.i: _deps/imgui-src/backends/imgui_impl_sdl3.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_sdl3.i

# target to preprocess a source file
_deps/imgui-src/backends/imgui_impl_sdl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/backends/imgui_impl_sdl3.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_sdl3.cpp.i

_deps/imgui-src/backends/imgui_impl_sdl3.s: _deps/imgui-src/backends/imgui_impl_sdl3.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_sdl3.s

# target to generate assembly for a file
_deps/imgui-src/backends/imgui_impl_sdl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/backends/imgui_impl_sdl3.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_sdl3.cpp.s

_deps/imgui-src/backends/imgui_impl_sdlrenderer3.o: _deps/imgui-src/backends/imgui_impl_sdlrenderer3.cpp.o
.PHONY : _deps/imgui-src/backends/imgui_impl_sdlrenderer3.o

# target to build an object file
_deps/imgui-src/backends/imgui_impl_sdlrenderer3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/backends/imgui_impl_sdlrenderer3.cpp.o
.PHONY : _deps/imgui-src/backends/imgui_impl_sdlrenderer3.cpp.o

_deps/imgui-src/backends/imgui_impl_sdlrenderer3.i: _deps/imgui-src/backends/imgui_impl_sdlrenderer3.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_sdlrenderer3.i

# target to preprocess a source file
_deps/imgui-src/backends/imgui_impl_sdlrenderer3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/backends/imgui_impl_sdlrenderer3.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_sdlrenderer3.cpp.i

_deps/imgui-src/backends/imgui_impl_sdlrenderer3.s: _deps/imgui-src/backends/imgui_impl_sdlrenderer3.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_sdlrenderer3.s

# target to generate assembly for a file
_deps/imgui-src/backends/imgui_impl_sdlrenderer3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/backends/imgui_impl_sdlrenderer3.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_sdlrenderer3.cpp.s

_deps/imgui-src/imgui.o: _deps/imgui-src/imgui.cpp.o
.PHONY : _deps/imgui-src/imgui.o

# target to build an object file
_deps/imgui-src/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui.cpp.o
.PHONY : _deps/imgui-src/imgui.cpp.o

_deps/imgui-src/imgui.i: _deps/imgui-src/imgui.cpp.i
.PHONY : _deps/imgui-src/imgui.i

# target to preprocess a source file
_deps/imgui-src/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui.cpp.i
.PHONY : _deps/imgui-src/imgui.cpp.i

_deps/imgui-src/imgui.s: _deps/imgui-src/imgui.cpp.s
.PHONY : _deps/imgui-src/imgui.s

# target to generate assembly for a file
_deps/imgui-src/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui.cpp.s
.PHONY : _deps/imgui-src/imgui.cpp.s

_deps/imgui-src/imgui_demo.o: _deps/imgui-src/imgui_demo.cpp.o
.PHONY : _deps/imgui-src/imgui_demo.o

# target to build an object file
_deps/imgui-src/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_demo.cpp.o
.PHONY : _deps/imgui-src/imgui_demo.cpp.o

_deps/imgui-src/imgui_demo.i: _deps/imgui-src/imgui_demo.cpp.i
.PHONY : _deps/imgui-src/imgui_demo.i

# target to preprocess a source file
_deps/imgui-src/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_demo.cpp.i
.PHONY : _deps/imgui-src/imgui_demo.cpp.i

_deps/imgui-src/imgui_demo.s: _deps/imgui-src/imgui_demo.cpp.s
.PHONY : _deps/imgui-src/imgui_demo.s

# target to generate assembly for a file
_deps/imgui-src/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_demo.cpp.s
.PHONY : _deps/imgui-src/imgui_demo.cpp.s

_deps/imgui-src/imgui_draw.o: _deps/imgui-src/imgui_draw.cpp.o
.PHONY : _deps/imgui-src/imgui_draw.o

# target to build an object file
_deps/imgui-src/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_draw.cpp.o
.PHONY : _deps/imgui-src/imgui_draw.cpp.o

_deps/imgui-src/imgui_draw.i: _deps/imgui-src/imgui_draw.cpp.i
.PHONY : _deps/imgui-src/imgui_draw.i

# target to preprocess a source file
_deps/imgui-src/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_draw.cpp.i
.PHONY : _deps/imgui-src/imgui_draw.cpp.i

_deps/imgui-src/imgui_draw.s: _deps/imgui-src/imgui_draw.cpp.s
.PHONY : _deps/imgui-src/imgui_draw.s

# target to generate assembly for a file
_deps/imgui-src/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_draw.cpp.s
.PHONY : _deps/imgui-src/imgui_draw.cpp.s

_deps/imgui-src/imgui_tables.o: _deps/imgui-src/imgui_tables.cpp.o
.PHONY : _deps/imgui-src/imgui_tables.o

# target to build an object file
_deps/imgui-src/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_tables.cpp.o
.PHONY : _deps/imgui-src/imgui_tables.cpp.o

_deps/imgui-src/imgui_tables.i: _deps/imgui-src/imgui_tables.cpp.i
.PHONY : _deps/imgui-src/imgui_tables.i

# target to preprocess a source file
_deps/imgui-src/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_tables.cpp.i
.PHONY : _deps/imgui-src/imgui_tables.cpp.i

_deps/imgui-src/imgui_tables.s: _deps/imgui-src/imgui_tables.cpp.s
.PHONY : _deps/imgui-src/imgui_tables.s

# target to generate assembly for a file
_deps/imgui-src/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_tables.cpp.s
.PHONY : _deps/imgui-src/imgui_tables.cpp.s

_deps/imgui-src/imgui_widgets.o: _deps/imgui-src/imgui_widgets.cpp.o
.PHONY : _deps/imgui-src/imgui_widgets.o

# target to build an object file
_deps/imgui-src/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_widgets.cpp.o
.PHONY : _deps/imgui-src/imgui_widgets.cpp.o

_deps/imgui-src/imgui_widgets.i: _deps/imgui-src/imgui_widgets.cpp.i
.PHONY : _deps/imgui-src/imgui_widgets.i

# target to preprocess a source file
_deps/imgui-src/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_widgets.cpp.i
.PHONY : _deps/imgui-src/imgui_widgets.cpp.i

_deps/imgui-src/imgui_widgets.s: _deps/imgui-src/imgui_widgets.cpp.s
.PHONY : _deps/imgui-src/imgui_widgets.s

# target to generate assembly for a file
_deps/imgui-src/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_widgets.cpp.s
.PHONY : _deps/imgui-src/imgui_widgets.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Minigin"
	@echo "... Portfolio_web"
	@echo "... SDL3-static"
	@echo "... SDL3_test"
	@echo "... SDL3_ttf-static"
	@echo "... SDL_uclibc"
	@echo "... glm"
	@echo "... imgui"
	@echo "... Minigin/FPSComponent.o"
	@echo "... Minigin/FPSComponent.i"
	@echo "... Minigin/FPSComponent.s"
	@echo "... Minigin/Font.o"
	@echo "... Minigin/Font.i"
	@echo "... Minigin/Font.s"
	@echo "... Minigin/GameObject.o"
	@echo "... Minigin/GameObject.i"
	@echo "... Minigin/GameObject.s"
	@echo "... Minigin/Gamepad.o"
	@echo "... Minigin/Gamepad.i"
	@echo "... Minigin/Gamepad.s"
	@echo "... Minigin/InputManager.o"
	@echo "... Minigin/InputManager.i"
	@echo "... Minigin/InputManager.s"
	@echo "... Minigin/MiniaudioSoundSystem.o"
	@echo "... Minigin/MiniaudioSoundSystem.i"
	@echo "... Minigin/MiniaudioSoundSystem.s"
	@echo "... Minigin/Minigin.o"
	@echo "... Minigin/Minigin.i"
	@echo "... Minigin/Minigin.s"
	@echo "... Minigin/RenderComponent.o"
	@echo "... Minigin/RenderComponent.i"
	@echo "... Minigin/RenderComponent.s"
	@echo "... Minigin/Renderer.o"
	@echo "... Minigin/Renderer.i"
	@echo "... Minigin/Renderer.s"
	@echo "... Minigin/ResourceManager.o"
	@echo "... Minigin/ResourceManager.i"
	@echo "... Minigin/ResourceManager.s"
	@echo "... Minigin/RotatorComponent.o"
	@echo "... Minigin/RotatorComponent.i"
	@echo "... Minigin/RotatorComponent.s"
	@echo "... Minigin/Scene.o"
	@echo "... Minigin/Scene.i"
	@echo "... Minigin/Scene.s"
	@echo "... Minigin/SceneManager.o"
	@echo "... Minigin/SceneManager.i"
	@echo "... Minigin/SceneManager.s"
	@echo "... Minigin/ServiceLocator.o"
	@echo "... Minigin/ServiceLocator.i"
	@echo "... Minigin/ServiceLocator.s"
	@echo "... Minigin/TextComponent.o"
	@echo "... Minigin/TextComponent.i"
	@echo "... Minigin/TextComponent.s"
	@echo "... Minigin/Texture2D.o"
	@echo "... Minigin/Texture2D.i"
	@echo "... Minigin/Texture2D.s"
	@echo "... Minigin/Transform.o"
	@echo "... Minigin/Transform.i"
	@echo "... Minigin/Transform.s"
	@echo "... Portfolio/Main.o"
	@echo "... Portfolio/Main.i"
	@echo "... Portfolio/Main.s"
	@echo "... _deps/imgui-src/backends/imgui_impl_sdl3.o"
	@echo "... _deps/imgui-src/backends/imgui_impl_sdl3.i"
	@echo "... _deps/imgui-src/backends/imgui_impl_sdl3.s"
	@echo "... _deps/imgui-src/backends/imgui_impl_sdlrenderer3.o"
	@echo "... _deps/imgui-src/backends/imgui_impl_sdlrenderer3.i"
	@echo "... _deps/imgui-src/backends/imgui_impl_sdlrenderer3.s"
	@echo "... _deps/imgui-src/imgui.o"
	@echo "... _deps/imgui-src/imgui.i"
	@echo "... _deps/imgui-src/imgui.s"
	@echo "... _deps/imgui-src/imgui_demo.o"
	@echo "... _deps/imgui-src/imgui_demo.i"
	@echo "... _deps/imgui-src/imgui_demo.s"
	@echo "... _deps/imgui-src/imgui_draw.o"
	@echo "... _deps/imgui-src/imgui_draw.i"
	@echo "... _deps/imgui-src/imgui_draw.s"
	@echo "... _deps/imgui-src/imgui_tables.o"
	@echo "... _deps/imgui-src/imgui_tables.i"
	@echo "... _deps/imgui-src/imgui_tables.s"
	@echo "... _deps/imgui-src/imgui_widgets.o"
	@echo "... _deps/imgui-src/imgui_widgets.i"
	@echo "... _deps/imgui-src/imgui_widgets.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/runner/work/AnaCarvalho-Portfolio/AnaCarvalho-Portfolio/build/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

