name: Web Build and Deploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14

      - name: Pre-build Emscripten Ports
        run: embuilder build freetype harfbuzz

      - name: Configure CMake
        run: emcmake cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build Project
        run: cmake --build build --config Release

      - name: Rename output to index.html
        run: |
          cd build
          if [ -f "Portfolio_web.html" ]; then
            mv Portfolio_web.html index.html
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build